# Use root/example as user/password credentials
version: '3.2'

services:
  db:
    image: mysql
    container_name: ${DB_HOST}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env.test
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports: 
      - "3306:3306"
    volumes: 
      - ./dbvolume:/var/lib/mysql