# Use root/example as user/password credentials
version: '3.2'

services:
  db:
    image: mysql
    container_name: ${DB_HOST}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports: 
      - "3306:3306"
    volumes: 
      - ./dbvolume:/var/lib/mysql
  api:
    build: .
    container_name: api
    restart: always
    depends_on:
      - db
    links: 
      - db
    env_file:
      - .env
    ports: 
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes: 
      - .:/usr/app
    command: yarn dev
    logging: 
      driver: "json-file"
      options: 
        max-size: "10m"
        max-file: "5"